### ISSUE TITLE
disable CRIPageLoadPromptInterval

### ISSUE THREAD

**Issue by clemorphy** [TruckMovers/cordova-plugin-remote-injection#14]
Hi again

So sorry to spam your issues list :)

In the documentation, you write this about the `CRIPageLoadPromptInterval `:

> If not wanting the prompt the user set the value to 0.

This is not working on Android (not tested on iOS yet)
When I set it to 0, it just uses a delay of 0, so the prompt appears immediately.

**Comment by bradleyjames** [comment]
> So sorry to spam your issues list :)

The feedback has been great.  Keep it up!

I'll try to look at this soon.
