### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jkeam** [TruckMovers/cordova-plugin-remote-injection#21]
First off, love the plugin.  Glad I stumbled upon it and it has been invaluable for my own project.  I was just curious about the roadmap for it?  What are your plans for the future?  What other features do you think will be coming down the pipe for this?

**Comment by bradleyjames** [comment]
Unless someone from TruckMovers (the company) chimes in I have no plans to enhance the plugin.  I left the company recently but plan to still address pull requests for bug fixes.

**Comment by jkeam** [comment]
Glad you'll still be involved as a maintainer 💯
