### ISSUE TITLE
CRIInjectFirstFiles issue

### ISSUE THREAD

**Issue by Graham-Phillips** [TruckMovers/cordova-plugin-remote-injection#23]
If I include www/cordova.js in the list of files to inject with CRIInjectFirstFiles I get an error thrown: cordova already defined

If I don't include it I get Uncaught ReferenceError: cordova is not defined

Which is the right way?

Just to add a bit more....  I'm getting no console logs from the index.js file I load. A plugin I have defined is loading (at least the library it includes is loading) and I get this is the console   "Could not find cordova.js script tag. Plugin loading may fail"  -- however, I can type cordova in the console and it traces ok. 

Currently got this
  <preference name="CRIInjectFirstFiles" value="assets/www/js/index.js,assets/www/plugins/cordova-plugin-myplugin/www/myplugin.js" />

**Comment by bradleyjames** [comment]
> Could not find cordova.js script tag. Plugin loading may fail

This message is a warning and I never got around to trying to address it.  If you can type cordova in the console while viewing a remote site the plugin has done its job.

I'm confused what state your in.  You shouldn't need to specify anything in CRIInjectFirstFiles in order for the plugin to inject cordova.

**Comment by Graham-Phillips** [comment]
Ah cool, thanks for the reply. No, I didn't think we should be manually injecting cordova to be honest, just trying every permutation.
