### ISSUE TITLE
CRIInjectFirstFiles is not working on IOS with multiple files list

### ISSUE THREAD

**Issue by silversonicaxel** [TruckMovers/cordova-plugin-remote-injection#26]
The plugin offer the chance to inject multiple files with the following command tag for the **config.xml**

`<preference name="CRIInjectFirstFiles" value="www/js/dist/vendor.js,www/js/dist/injected.js" />`

For Android, everything works fine, javascript is injected into the remote site.
For IOS it is not the case. I can confirm that for already two projects (two different work projects) the second file, maybe also the first but we did not check this scenario, is not injected at all.
The solution of the problem was using just one file, so this 

`<preference name="CRIInjectFirstFiles" value="www/js/dist/injected.js" />`

It works but it is not in line with the docs of the plugin.

**Comment by bradleyjames** [comment]
Thanks for the report @silversonicaxel but I'm not able to reproduce.  Can you provide an example project that shows the behavior?

**Comment by bradleyjames** [comment]
Closing as a result of no response.

**Comment by ycwjjjj** [comment]
I have compile error even only one file injection. Cordova ios version 4.4.0.

**Comment by kumarsanjay435** [comment]
Injection is working for the landing component of the app. Other places native calls are not working. Please help
