### ISSUE TITLE
How do I inject and use cordova plugins ?

### ISSUE THREAD

**Issue by alexandrzavalii** [TruckMovers/cordova-plugin-remote-injection#37]
After I moved my webview on the server I have many plugins not available.

For some reason there are few that I can access.
cordova.plugins:
> Keyboard: function()
> brightness: {getBrightness: function, setBrightness: function, setKeepScreenOn: function}
> screenorientation:

window.plugins:

> orientationLock

In my javascript I have a call to 'window.plugins.streamingMedia.playVideo

How would I make all the cordova plugin available the same way they where previously ?
Can I inject them using this plugin ?

**Comment by Kevga** [comment]
I have the same issue. Have you found a solution to this?
