### ISSUE TITLE
Link opens built in Safari

### ISSUE THREAD

**Issue by morioma** [TruckMovers/cordova-plugin-remote-injection#4]
Hi, 
It's me again. Thanks for the 0.2.0 update. It works with all my plugins.

Since I upgrade to cordova ios 4.1.1. I noticed a behavior change, when click on a link (a tag) like this `<a href="#">Link</a>`, built in safari will be opened instead of navigating the WebView to that page.

I thought this is a easy things to fix but after messing with things like `<allow-navigation />` `<access origin="*" />` for a while I still can't make this opening safari behavior go away.

This behavior doesn't exist on corodva ios 3.9.2 with previous version of this plugin. This behavior also doesn't exist when not using external website but use traditional 'stuff in www' folder.

Do you any insight on this issue?

Sincerely,

**Comment by bradleyjames** [comment]
Have you tried uninstalling cordova-plugin-remote-injection to see if it's the culprit?  I just tried on a test project and I see the behavior with and without our plugin meaning I don't think we created this behavior.

As an aside we use the [InAppBrowser plugin](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-inappbrowser/index.html) to be able to control how the app behaves with links.  All of our links are created via JS though so we're using `window.open()`.

I don't have the time right now to dive into it but if you see the same result without our plugin the general [cordova community](https://cordova.apache.org/contribute/) might be able to help as well.  I'm not trying to put you off, just saying you might get quicker help from them.

I'd like to know the answer myself and will dig into it when I get a free moment.  Please post back with anything you find!

**Comment by morioma** [comment]
Sure. I'll dig into this more and keep you posted.

**Comment by morioma** [comment]
Thanks for point out cordova community, I found the solution [here](https://issues.apache.org/jira/browse/CB-10859).

The issue is not related this plugin. The issue is related opening external website on Cordova ios 4+.
Basically remove 
    `<allow-intent href="http://*/*" />`
    `<allow-intent href="https://*/*" />`
from cordova config.xml solved the problem. 
I guess because the url of external website falls into the intent filter, so a open link intent is send to the ios system. Handle navigation in JavaScript could avoid this too.

I'll close this issue now. :smiley:

**Comment by bradleyjames** [comment]
Great, thanks for following up.
