### ISSUE TITLE
Support for wkwebview

### ISSUE THREAD

**Issue by twang333** [TruckMovers/cordova-plugin-remote-injection#8]

**Comment by bradleyjames** [comment]
Can you please provide some more details?  Why is this beneficial, what will it provide, etc.?  Also links to relevant docs would be great.

**Comment by bradleyjames** [comment]
Without details I'm not sure what to do with this.  If I had extra time I'd do some digging but I don't have it right now. If you have information on errors you're seeing, what platform, etc. it will give me some place to start.

Until then closing.

**Comment by Klathmon** [comment]
I'd like to +1 this request.

Starting with cordova 6 (I believe), Cordova has allowed the developer to switch out the rendering engine on ios. It can be switched from UIWebView to WKWebView.

WKWebView uses a much faster javascript engine, and has some other benefits, but has a different API. It's not a show-stopper that this plugin doesn't work with WKWebView, but having to fallback to UIWebView is making the whole application sluggish (it's a pretty javascript heavy application).

Currently this application does nothing when used with a WKWebView. I'm assuming it needs some changes to either use Cordova's "renderer independent" API, or it needs to be custom coded for WKWebView support.

**Comment by bradleyjames** [comment]
@Klathmon, thanks for the info.  Reopening.

**Comment by Klathmon** [comment]
So I decided to take a crack at it. First time ever working with objective-c, and I managed to get something together for our internal usage. 

I kind of went "scorched earth" on this and removed literally everything except for the bare minimum I needed, so this ONLY injects the cordova.js and plugin files into any remote app, and it ONLY works with WKWebView. The fork is located [here](https://github.com/PCSTrac/cordova-plugin-remote-injection).

It shouldn't be that tough at all to support both WKWebView and UIWebView at the same time. In case anyone else wants to pickup where I left off, I'm going to dump a few links I found useful.

* [StackOverflow answer with some UIWebView methods and their "kinda-sorta-the-same" WKWebView counterparts](http://stackoverflow.com/questions/26128815/uiwebview-delegate-method-shouldstartloadwithrequest-equivalent-in-wkwebview/26134994#26134994)
* [WKWebView Object docs from Apple](https://developer.apple.com/reference/webkit/wkwebview?language=objc)
* [WKNavigationDelegate Object docs from Apple. This mostly replaces the UIWebViewDelegate](https://developer.apple.com/reference/webkit/wknavigationdelegate?language=objc)
* [Upgrade notes for Cordova-iOS@4. Specifically the way to cast cordova's `webView` property to either WKWebView or UIWebView depending on what you need.
* I don't have a good answer off the top of my head on how to figure out which engine the user is trying to use, but it looks like the [`cordova-plugin-keyboard` has figured it out, but it's a bit above my skill level in objective-c for now...](https://github.com/cjpearson/cordova-plugin-keyboard/blob/44e3ef9371ee496d9496e7df6f43f89261ea90f8/src/ios/CDVKeyboard.m#L113)

**Comment by bradleyjames** [comment]
You just made my day, awesome work.  I'm trying to block off a little time to get to this.

**Comment by Klathmon** [comment]
Like I said, I got it working enough that I'm happy, so don't feel like you need to rush for me!

**Comment by bradleyjames** [comment]
I believe I have this implemented in the branch [issue-8](https://github.com/TruckMovers/cordova-plugin-remote-injection/tree/issue-8).  I have more testing to do but please check it and see if it addresses your needs or if you run into issues.

This is a passive change and should auto detect the type of web view in use and react accordingly.

**Comment by Klathmon** [comment]
That works fantastically! Zero changes needed on my part, and I now have the full functionality with WkWebView.

Thanks a ton for following up on this!

**Comment by bradleyjames** [comment]
Glad it works for you.  I'll get it merged into master and pushed to npm this week.

**Comment by bradleyjames** [comment]
This has been merged into mainline and is in the 0.4.0 release.
