### ISSUE TITLE
Could not find cordova.js script tag. Plugin loading may fail.

### ISSUE THREAD

**Issue by fevxie** [TruckMovers/cordova-plugin-remote-injection#9]
hi,

   When I run plugin on cordova 6.3 , cordova android 5.2.1 with remote url which config like this 
```
<content src="https://xxx.com" />. 
```
The remote web page meet an error:

data:text/javascript;base64,ZnVuY3Rpb24gdGVzdCgpIHsKICAgIGFsZXJ0KCd0ZXN0Jyk7Cn0KLy8gUGxhdGZvcm06IGF…:1920 Could not find. Plugin loading may fail.

@bradleyjames  Can you give me some advices. 

Thanks.

**Comment by bradleyjames** [comment]
I may recall seeing something like this before but it was just an info message, not an actual error.  Is cordova being injected or are you seeing a issue?

**Comment by fevxie** [comment]
As you said,  It just an info message and  the plugin work as expected.  Still thanks for your work and quickly reply.
